name: 🐛 Bug Report
description: Report a bug or unexpected behavior in LightRFT
title: "[Bug]: "
labels: ["bug"]

body:
- type: markdown
  attributes:
    value: >
      #### Before submitting an issue, please make sure the issue hasn't been already addressed by searching through [the existing and past issues](https://github.com/opendilab/LightRFT/issues?q=is%3Aissue+sort%3Acreated-desc+).

- type: markdown
  attributes:
    value: |
      ⚠️ **SECURITY WARNING:** Please review any text you paste to ensure it does not contain sensitive information such as:
      - API tokens or keys (e.g., Hugging Face tokens, OpenAI API keys, W&B API keys)
      - Passwords or authentication credentials
      - Private URLs or endpoints
      - Personal or confidential data

      Consider redacting or replacing sensitive values with placeholders like `<YOUR_TOKEN_HERE>` when sharing configuration or code examples.

- type: textarea
  attributes:
    label: Your current environment
    description: |
      Please provide detailed environment information to help us reproduce the issue.
    value: |
      - LightRFT Version (git commit hash):
      - Python Version:
      - PyTorch Version:
      - CUDA Version:
      - GPU Model (and number of GPUs):
      - Operating System:
      - Distributed Backend (FSDP/DeepSpeed):
      - Inference Engine (vLLM/SGLang/None):
      - vLLM Version (if applicable):
      - SGLang Version (if applicable):
      - Other relevant packages:
  validations:
    required: true

- type: textarea
  attributes:
    label: 🐛 Describe the bug
    description: |
      Please provide a clear and concise description of what the bug is.

      If relevant, add a **minimal** reproducible example so that we can reproduce the error by running the code. Please take time to trim down any irrelevant code to help us debug efficiently. We expect to copy-paste your code and get the same result as you did.

      For example:
      ```python
      from lightrft.trainer import SPMDPPOTrainer
      from lightrft.models import Actor

      # Minimal code to reproduce the issue
      trainer = SPMDPPOTrainer(...)
      trainer.fit()
      ```

      If the code is too long, feel free to put it in a public gist and link it in the issue: https://gist.github.com

      Please also paste or describe the results you observe instead of the expected results. If you observe an error, please paste the error message including the **full** traceback of the exception.

      For debugging training issues, please consider:
      - Checking W&B logs if available
      - Reviewing trajectory files if saved
      - Enabling verbose logging with appropriate log levels
    placeholder: |
      A clear and concise description of what the bug is.

      **Reproduction code:**
      ```python
      # Minimal code to reproduce the problem
      ```

      **Error message:**
      ```
      The error message you got, with the full traceback
      ```
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected Behavior
    description: |
      What did you expect to happen?
    placeholder: |
      Describe what should happen instead.
  validations:
    required: true

- type: textarea
  attributes:
    label: Training Configuration
    description: |
      If this is a training-related bug, please provide your training configuration or command.

      Include key parameters like:
      - Model name/path
      - Algorithm (GRPO, GSPO, etc.)
      - Batch sizes (TBS, RBS, micro batch sizes)
      - Distributed training settings
      - Inference engine settings
      - Any other relevant parameters
    render: bash
    placeholder: |
      # Training command or script:
      bash examples/gsm8k_geo3k/run_grpo_gsm8k_qwen2.5_0.5b.sh

      # Or key configuration:
      --model_name_or_path Qwen/Qwen2.5-0.5B-Instruct \
      --advantage_estimator group_norm \
      --n_samples_per_prompt 8 \
      --fsdp \
      --zero_stage 3 \
      --rm_use_engine \
      ...

- type: textarea
  attributes:
    label: Logs
    description: |
      Please provide relevant log output. For training issues, include:
      - Console output showing the error
      - Relevant portions of training logs
      - W&B logs if available

      Use code blocks for better formatting.
    render: shell
    placeholder: |
      Paste relevant logs here

- type: dropdown
  id: severity
  attributes:
    label: Severity
    description: How severe is this bug?
    options:
      - Critical (Training crashes immediately, data loss, or blocking issue)
      - High (Major functionality broken, no workaround)
      - Medium (Feature partially working, workaround available)
      - Low (Minor issue, easy workaround)
  validations:
    required: true

- type: textarea
  attributes:
    label: Additional Context
    description: |
      Add any other context about the problem:
      - Does this happen consistently or intermittently?
      - Did this work in a previous version?
      - Related issues or discussions
      - Screenshots if applicable

- type: markdown
  attributes:
    value: >
      Thanks for reporting 🙏!

- type: checkboxes
  id: confirmation
  attributes:
    label: Before submitting a new issue...
    options:
      - label: Make sure you already searched for relevant issues, and checked the [FAQ](https://github.com/opendilab/LightRFT/tree/main/docs/source/best_practice/faq.md) and [troubleshooting guide](https://github.com/opendilab/LightRFT/tree/main/docs/source/best_practice/troubleshooting.md).
        required: true
